apiVersion: v1
kind: Pod
metadata:
  name: testing
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo
    image: centos
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  restartPolicy: OnFailure
 
