apiVersion: v1
kind: Pod
metadata:
  name: testing1
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo Ahsan; sleep 10;done"]
  restartPolicy: OnFailure
