apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-0
  labels:
    app: postgres-db-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-0
  template:
    metadata:
      labels:
        app: postgres-db-0
    spec:
      containers:
      - name: postgres-db-0
        image: docker.afiniti.com/postgres-airo:latest
        ports:
        - containerPort: 5432
        env:
         - name: POSTGRES_USER
           value: test
         - name: POSTGRES_PASSWORD
           value: nopassword
         - name: POSTGRES_MULTIPLE_DATABASES
           value: test.test1
